# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "machine1" do |machine1|
    machine1.vm.box = "ubuntu/bionic64"

    machine1.vm.hostname = "machine1"
    machine1.vm.network "private_network", ip: "10.0.0.100"

    machine1.vm.provision "shell", :inline => "echo '10.0.0.101 machine2' >> /etc/hosts"
    machine1.vm.provision "shell", path: "bootstrap-machine1.sh"

    machine1.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "1024"
    end
  end

  config.vm.define "machine2" do |machine2|
    machine2.vm.box = "ubuntu/bionic64"

    machine2.vm.hostname = "machine2"
    machine2.vm.network "private_network", ip: "10.0.0.101"

    machine2.vm.provision "shell", :inline => "echo '10.0.0.100 machine1' >> /etc/hosts"
    machine2.vm.provision "shell", path: "bootstrap-machine2.sh"

    machine2.vm.provider "virtualbox" do |vb|
      vb.cpus = "1"
      vb.memory = "1024"
    end
  end
end